# Generated by Django 6.0.3 on 2026-03-22 00:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('memorization_rating', models.CharField(choices=[('excellent', '⭐ ممتاز'), ('good', '✅ جيد'), ('average', '➖ متوسط'), ('weak', '⚠️ يحتاج متابعة')], max_length=15, verbose_name='تقييم الحفظ')),
                ('memorization_notes', models.TextField(blank=True, verbose_name='ملاحظات الحفظ')),
                ('behavior_rating', models.CharField(choices=[('excellent', '⭐ ممتاز'), ('good', '✅ جيد'), ('average', '➖ متوسط'), ('weak', '⚠️ يحتاج متابعة')], max_length=15, verbose_name='تقييم السلوك')),
                ('commitment_rating', models.CharField(choices=[('excellent', '⭐ ممتاز'), ('good', '✅ جيد'), ('average', '➖ متوسط'), ('weak', '⚠️ يحتاج متابعة')], max_length=15, verbose_name='تقييم الالتزام')),
                ('behavior_notes', models.TextField(blank=True, verbose_name='ملاحظات السلوك')),
                ('is_distinguished', models.BooleanField(default=False, verbose_name='متميز')),
                ('needs_attention', models.BooleanField(default=False, verbose_name='يحتاج متابعة')),
                ('general_notes', models.TextField(blank=True, verbose_name='ملاحظات عامة لولي الأمر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تقييم طالب',
                'verbose_name_plural': 'تقييمات الطلاب',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('homework', models.TextField(verbose_name='الواجب المطلوب')),
                ('memorization_task', models.TextField(blank=True, verbose_name='المطلوب حفظه')),
                ('extra_notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['hall_supervisor', 'general_supervisor', 'general_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups_created', to=settings.AUTH_USER_MODEL, verbose_name='كتبه')),
            ],
            options={
                'verbose_name': 'متابعة يومية',
                'verbose_name_plural': 'المتابعات اليومية',
                'ordering': ['-date'],
            },
        ),
    ]
