# Generated by Django 6.0.3 on 2026-03-22 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('halls', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfollowup',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_followups', to='halls.hall', verbose_name='القاعة'),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='students.student', verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'general_supervisor', 'general_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='المعلم'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyfollowup',
            unique_together={('hall', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='studentevaluation',
            unique_together={('student', 'date')},
        ),
    ]
