# Generated by Django 6.0.3 on 2026-03-22 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halls', '0001_initial'),
        ('quran', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('min_age', models.PositiveIntegerField(verbose_name='الحد الأدنى للسن')),
                ('max_age', models.PositiveIntegerField(verbose_name='الحد الأقصى للسن')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'فئة عمرية',
                'verbose_name_plural': 'الفئات العمرية',
                'ordering': ['order', 'min_age'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='اسم العائلة')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='صورة الطالب')),
                ('uses_bus', models.BooleanField(default=False, verbose_name='يشترك في الباص')),
                ('bus_notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات الباص')),
                ('status', models.CharField(choices=[('pending', 'في انتظار التسكين'), ('active', 'نشط'), ('inactive', 'غير نشط')], default='pending', max_length=20, verbose_name='حالة الطالب')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات عامة')),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.agegroup', verbose_name='الفئة العمرية')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='halls.hall', verbose_name='القاعة')),
                ('memorized_surahs', models.ManyToManyField(blank=True, related_name='memorized_by', to='quran.surah', verbose_name='السور المحفوظة')),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='ولي الأمر')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
