# Generated by Django 6.0.3 on 2026-04-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'في انتظار التسكين'), ('active', 'نشط'), ('inactive', 'غير نشط'), ('rejected', 'مرفوض لعدم وجود قاعة مناسبة')], default='pending', max_length=20, verbose_name='حالة الطالب'),
        ),
    ]
