# Generated by Django 6.0.3 on 2026-05-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم موبايل الطوارئ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='اسم الرباعي'),
        ),
    ]
