# Generated by Django 6.0.3 on 2026-05-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_emergency_phone_alter_student_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_picture',
        ),
    ]
