# Generated by Django 6.0.3 on 2026-05-20 14:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('parent', 'first_name', 'last_name')},
        ),
    ]
