# Generated by Django 6.0.3 on 2026-03-22 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='مقرأة القرآن الكريم', max_length=200, verbose_name='اسم المقرأة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='الشعار')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('description', models.TextField(blank=True, verbose_name='نبذة عن المقرأة')),
                ('allow_registration', models.BooleanField(default=True, verbose_name='السماح بالتسجيل')),
                ('auto_assign_halls', models.BooleanField(default=True, verbose_name='التسكين التلقائي')),
                ('max_age_limit', models.PositiveIntegerField(default=15, verbose_name='الحد الأقصى للسن')),
                ('min_age_limit', models.PositiveIntegerField(default=3, verbose_name='الحد الأدنى للسن')),
                ('attendance_start_time', models.TimeField(default='08:00', verbose_name='وقت بداية الحضور')),
                ('late_threshold_minutes', models.PositiveIntegerField(default=15, verbose_name='دقائق التأخير')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساب')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
