# Generated by Django 6.0.3 on 2026-04-19 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sitesettings'),
        ('halls', '0003_hall_current_juz_hall_general_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_attendance',
            field=models.BooleanField(default=False, verbose_name='إدارة الحضور'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_evaluations',
            field=models.BooleanField(default=False, verbose_name='إدارة التقييمات'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_halls',
            field=models.BooleanField(default=False, verbose_name='إدارة القاعات'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_settings',
            field=models.BooleanField(default=False, verbose_name='إدارة الإعدادات'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_students',
            field=models.BooleanField(default=False, verbose_name='إدارة الطلاب'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='إدارة المستخدمين'),
        ),
        migrations.CreateModel(
            name='GeneralSupervisorHallAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_supervisor_assignments', to='halls.hall', verbose_name='القاعة')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'general_supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='hall_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المشرف العام')),
            ],
            options={
                'verbose_name': 'إسناد قاعة لمشرف عام',
                'verbose_name_plural': 'إسنادات القاعات للمشرفين العامين',
                'unique_together': {('supervisor', 'hall')},
            },
        ),
    ]
