# Generated by Django 6.0.3 on 2026-03-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='رقم السورة')),
                ('name_arabic', models.CharField(max_length=50, verbose_name='اسم السورة')),
                ('name_english', models.CharField(max_length=50, verbose_name='الاسم بالإنجليزي')),
                ('juz', models.PositiveIntegerField(verbose_name='الجزء')),
                ('total_verses', models.PositiveIntegerField(verbose_name='عدد الآيات')),
            ],
            options={
                'verbose_name': 'سورة',
                'verbose_name_plural': 'سور القرآن الكريم',
                'ordering': ['number'],
            },
        ),
    ]
