# Generated by Django 6.0.3 on 2026-03-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القاعة')),
                ('location', models.CharField(max_length=200, verbose_name='موقع القاعة')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name='أقصى عدد للطلاب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قاعة',
                'verbose_name_plural': 'القاعات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HallSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('saturday', 'السبت'), ('sunday', 'الأحد'), ('monday', 'الاثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس'), ('friday', 'الجمعة')], max_length=15, verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
            ],
            options={
                'verbose_name': 'جدول قاعة',
                'verbose_name_plural': 'جداول القاعات',
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('description', models.TextField(blank=True, verbose_name='وصف المادة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد الدراسية',
            },
        ),
    ]
