# Generated by Django 6.0.3 on 2026-03-22 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halls', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halls', to='students.agegroup', verbose_name='الفئة العمرية'),
        ),
        migrations.AddField(
            model_name='hall',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'hall_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervising_halls', to=settings.AUTH_USER_MODEL, verbose_name='مشرف القاعة'),
        ),
        migrations.AddField(
            model_name='hall',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_halls', to=settings.AUTH_USER_MODEL, verbose_name='المعلم'),
        ),
        migrations.AddField(
            model_name='hallschedule',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='halls.hall', verbose_name='القاعة'),
        ),
        migrations.AddField(
            model_name='hallschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.subject', verbose_name='المادة'),
        ),
        migrations.AlterUniqueTogether(
            name='hallschedule',
            unique_together={('hall', 'day', 'start_time')},
        ),
    ]
