# Generated by Django 6.0.3 on 2026-04-19 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='current_juz',
            field=models.PositiveIntegerField(default=30, verbose_name='الجزء الحالي الذي تبدأ منه القاعة'),
        ),
        migrations.AddField(
            model_name='hall',
            name='general_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'general_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_halls', to=settings.AUTH_USER_MODEL, verbose_name='المشرف العام المسؤول'),
        ),
        migrations.AddField(
            model_name='hall',
            name='required_completed_juz_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الأجزاء المطلوبة قبل دخول القاعة'),
        ),
    ]
