# Generated by Django 6.0.3 on 2026-05-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_hall_current_juz_hall_general_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallschedule',
            name='day',
            field=models.CharField(choices=[('sunday', 'الأحد'), ('tuesday', 'الثلاثاء'), ('thursday', 'الخميس')], max_length=15, verbose_name='اليوم'),
        ),
    ]
