# Generated by Django 6.0.3 on 2026-05-11 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_alter_hallschedule_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الجدول')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'جدول نموذجي',
                'verbose_name_plural': 'الجداول النموذجية',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hall',
            name='schedule_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halls', to='halls.scheduletemplate', verbose_name='الجدول النموذجي'),
        ),
        migrations.CreateModel(
            name='ScheduleTemplateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sunday', 'الأحد'), ('tuesday', 'الثلاثاء'), ('thursday', 'الخميس')], max_length=15, verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.subject', verbose_name='المادة')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='halls.scheduletemplate', verbose_name='الجدول')),
            ],
            options={
                'verbose_name': 'حصة في الجدول',
                'verbose_name_plural': 'حصص الجداول',
                'ordering': ['day', 'start_time'],
                'unique_together': {('template', 'day', 'start_time')},
            },
        ),
    ]
