# Generated by Django 6.0.3 on 2026-03-22 00:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('excused', 'غياب بعذر')], default='present', max_length=10, verbose_name='الحالة')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حضور طالب',
                'verbose_name_plural': 'حضور الطلاب',
                'ordering': ['-date', 'hall'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('excused', 'غياب بعذر')], default='present', max_length=10, verbose_name='الحالة')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role__in': ['general_supervisor', 'general_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attendances_recorded', to=settings.AUTH_USER_MODEL, verbose_name='سجّله')),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'hall_supervisor']}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendances', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'حضور موظف',
                'verbose_name_plural': 'حضور الموظفين',
                'ordering': ['-date', 'staff'],
            },
        ),
    ]
