# Generated by Django 6.0.3 on 2026-03-22 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('halls', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='halls.hall', verbose_name='القاعة'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='recorded_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['hall_supervisor', 'general_supervisor', 'general_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attendances_recorded', to=settings.AUTH_USER_MODEL, verbose_name='سجّله'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='الطالب'),
        ),
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together={('staff', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'date')},
        ),
    ]
