# Generated by Django 6.0.3 on 2026-06-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_staffattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف'),
        ),
    ]
